name: CI for VDT2024 Web Application

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Minhtuan03
          MYSQL_DATABASE: vdt
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' 

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Maven
        run: |
          mvn -B install -DskipTests

      - name: Run tests
        env:
          MYSQL_HOST: localhost
          MYSQL_DATABASE: vdt
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: Minhtuan03
        run: |
          mvn test
